// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	GetByShortKey(ctx context.Context, shortKey string) (string, error)
	SaveShortKey(ctx context.Context, arg SaveShortKeyParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
