// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const getByShortKey = `-- name: GetByShortKey :one
SELECT long_url
FROM url_shortener.links 
WHERE short_key = $1
`

func (q *Queries) GetByShortKey(ctx context.Context, shortKey string) (string, error) {
	row := q.db.QueryRow(ctx, getByShortKey, shortKey)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}

const saveShortKey = `-- name: SaveShortKey :execresult
INSERT INTO url_shortener.links (short_key, long_url)
VALUES ($1, $2)
ON CONFLICT (short_key) DO NOTHING
`

type SaveShortKeyParams struct {
	ShortKey string `json:"short_key"`
	LongUrl  string `json:"long_url"`
}

func (q *Queries) SaveShortKey(ctx context.Context, arg SaveShortKeyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveShortKey, arg.ShortKey, arg.LongUrl)
}
